@url = https://8080-danisborges-trabfinalap-934ygovc6ts.ws-us120.gitpod.io

### Listar todos os alunos
GET {{url}}/alunos

### Buscar aluno por ID
GET {{url}}/alunos/1

### Criar novo aluno (registro)
POST {{url}}/alunos
Content-Type: application/json

{
    "nome": "Maria Souza",
    "email": "Maria@email.com",
    "senha": "345678"
}

### Deletar aluno
DELETE {{url}}/alunos/1