### Obter detalhes de um módulo
@url = https://8080-danisborges-trabfinalap-934ygovc6ts.ws-us120.gitpod.io
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBUEkgQ3Vyc29zIiwic3ViIjoidGVzdGUzQHRlc3RlLmNvbSIsImlkIjoyLCJleHAiOjE3NDkwNjg2OTZ9.j-7o-NM72D4r60N6ILKmD9SM8pI3ite7PGpyUdn9OFo
### Listar módulos de um curso


GET {{url}}/cursos/1/modulos
Authorization: Bearer {{token}}

### Obter detalhes de um módulo
GET {{url}}/modulos/1
Authorization: Bearer {{token}}
###
### Criar novo módulo para um curso

POST {{url}}/cursos/2/modulos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "titulo": "Introdução ao Spring Boot",
  "descricao": "Fundamentos e configuração inicial do Spring Boot"
}

### Atualizar módulo
PUT {{url}}/modulos/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "titulo": "Introdução ao Spring Boot - Atualizado",
  "descricao": "Fundamentos, configuração e boas práticas com Spring Boot"
}

### Excluir módulo
DELETE {{url}}/modulos/1
Authorization: Bearer {{token}}